bcu.o: bcu.c app.h include/sleep.h include/emu.h include/fram.h \
 include/bcu.h include/iomem.h include/sram.h include/usbc.h \
 include/flash.h include/lcdc.h include/bcu.h include/core.h \
 include/c33209e.h include/vector.h include/piemu.h
core.o: core.c app.h include/sleep.h include/emu.h include/fram.h \
 include/bcu.h include/iomem.h include/sram.h include/usbc.h \
 include/flash.h include/lcdc.h include/bcu.h include/core.h \
 include/c33209e.h include/vector.h include/piemu.h
emu.o: emu.c app.h include/sleep.h include/emu.h include/fram.h \
 include/bcu.h include/iomem.h include/sram.h include/usbc.h \
 include/flash.h include/lcdc.h include/bcu.h include/core.h \
 include/c33209e.h include/vector.h include/piemu.h
flash.o: flash.c app.h include/sleep.h include/emu.h include/fram.h \
 include/bcu.h include/iomem.h include/sram.h include/usbc.h \
 include/flash.h include/lcdc.h include/bcu.h include/core.h \
 include/c33209e.h include/vector.h include/piemu.h
fram.o: fram.c app.h include/sleep.h include/emu.h include/fram.h \
 include/bcu.h include/iomem.h include/sram.h include/usbc.h \
 include/flash.h include/lcdc.h include/bcu.h include/core.h \
 include/c33209e.h include/vector.h include/piemu.h
iomem.o: iomem.c app.h include/sleep.h include/emu.h include/fram.h \
 include/bcu.h include/iomem.h include/sram.h include/usbc.h \
 include/flash.h include/lcdc.h include/bcu.h include/core.h \
 include/c33209e.h include/vector.h include/piemu.h
lcdc.o: lcdc.c app.h include/sleep.h include/emu.h include/fram.h \
 include/bcu.h include/iomem.h include/sram.h include/usbc.h \
 include/flash.h include/lcdc.h include/bcu.h include/core.h \
 include/c33209e.h include/vector.h include/piemu.h
piemu.o: piemu.c app.h include/sleep.h include/emu.h include/fram.h \
 include/bcu.h include/iomem.h include/sram.h include/usbc.h \
 include/flash.h include/lcdc.h include/bcu.h include/core.h \
 include/c33209e.h include/vector.h include/piemu.h pfi.h
sram.o: sram.c app.h include/sleep.h include/emu.h include/fram.h \
 include/bcu.h include/iomem.h include/sram.h include/usbc.h \
 include/flash.h include/lcdc.h include/bcu.h include/core.h \
 include/c33209e.h include/vector.h include/piemu.h
usbc.o: usbc.c app.h include/sleep.h include/emu.h include/fram.h \
 include/bcu.h include/iomem.h include/sram.h include/usbc.h \
 include/flash.h include/lcdc.h include/bcu.h include/core.h \
 include/c33209e.h include/vector.h include/piemu.h
