bcu.obj: bcu.c app.h  \
  ./include/emu.h ./include/fram.h \
  ./include/iomem.h ./include/sram.h ./include/usbc.h ./include/flash.h \
  ./include/lcdc.h ./include/bcu.h ./include/core.h ./include/c33209e.h \
  ./include/vector.h ./include/piemu.h
core.obj: core.c app.h \
  ./include/emu.h ./include/fram.h \
  ./include/iomem.h ./include/sram.h ./include/usbc.h ./include/flash.h \
  ./include/lcdc.h ./include/bcu.h ./include/core.h ./include/c33209e.h \
  ./include/vector.h ./include/piemu.h
emu.obj: emu.c app.h ./include/emu.h ./include/fram.h \
  ./include/iomem.h ./include/sram.h ./include/usbc.h ./include/flash.h \
  ./include/lcdc.h ./include/bcu.h ./include/core.h ./include/c33209e.h \
  ./include/vector.h ./include/piemu.h
flash.obj: flash.c app.h ./include/emu.h ./include/fram.h \
  ./include/iomem.h ./include/sram.h ./include/usbc.h ./include/flash.h \
  ./include/lcdc.h ./include/bcu.h ./include/core.h ./include/c33209e.h \
  ./include/vector.h ./include/piemu.h
fram.obj: fram.c app.h ./include/emu.h ./include/fram.h \
  ./include/iomem.h ./include/sram.h ./include/usbc.h ./include/flash.h \
  ./include/lcdc.h ./include/bcu.h ./include/core.h ./include/c33209e.h \
  ./include/vector.h ./include/piemu.h
iomem.obj: iomem.c app.h ./include/emu.h ./include/fram.h \
  ./include/iomem.h ./include/sram.h ./include/usbc.h ./include/flash.h \
  ./include/lcdc.h ./include/bcu.h ./include/core.h ./include/c33209e.h \
  ./include/vector.h ./include/piemu.h
lcdc.obj: lcdc.c app.h ./include/emu.h ./include/fram.h \
  ./include/iomem.h ./include/sram.h ./include/usbc.h ./include/flash.h \
  ./include/lcdc.h ./include/bcu.h ./include/core.h ./include/c33209e.h \
  ./include/vector.h ./include/piemu.h
main.obj: main.c app.h ./include/emu.h ./include/fram.h \
  ./include/iomem.h ./include/sram.h ./include/usbc.h ./include/flash.h \
  ./include/lcdc.h ./include/bcu.h ./include/core.h ./include/c33209e.h \
  ./include/vector.h ./include/piemu.h
piemu.obj: piemu.c app.h ./include/emu.h ./include/fram.h \
  ./include/iomem.h ./include/sram.h ./include/usbc.h ./include/flash.h \
  ./include/lcdc.h ./include/bcu.h ./include/core.h ./include/c33209e.h \
  ./include/vector.h ./include/piemu.h pfi.h
sram.obj: sram.c app.h ./include/emu.h ./include/fram.h \
  ./include/iomem.h ./include/sram.h ./include/usbc.h ./include/flash.h \
  ./include/lcdc.h ./include/bcu.h ./include/core.h ./include/c33209e.h \
  ./include/vector.h ./include/piemu.h
usbc.obj: usbc.c app.h ./include/emu.h ./include/fram.h \
  ./include/iomem.h ./include/sram.h ./include/usbc.h ./include/flash.h \
  ./include/lcdc.h ./include/bcu.h ./include/core.h ./include/c33209e.h \
  ./include/vector.h ./include/piemu.h
