
all: $(TARGET)

clean:
	rm -f *.o *.a
	for dir in $(EXT_DIRS); do rm -rf $$dir/*.o $$dir/*.a; done

depend:

Makefile.dep: Makefile.in
	$(CC) -MM $(CFLAGS) $(addsuffix .c,$(basename $(OBJS))) > Makefile.dep

%.o: %.c
	$(CC) -c $(CFLAGS) -o $@ $<

